# See https://pre-commit.com for more information
repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: sh -c 'GOFLAGS=-mod=vendor golangci-lint run "$@"' --
        language: system
        types: [go]

  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.2.2
    hooks:
      - id: tofu_tflint
      - id: tofu_validate